[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.2.0"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL -D -F"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL -D -F"

[context.next]
  command = "npm run build -D -F"

[context.next.environment]
  HUGO_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://docs.darcy.ai/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing",
      "yandex"
    ]

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "SAMEORIGIN"
Referrer-Policy = "strict-origin"
Feature-Policy = "geolocation 'self'"
Cache-Control = "public, max-age=31536000"
Access-Control-Allow-Origin = "*"

Content-Security-Policy = '''
      default-src 'self' 'unsafe-inline' docs.darcy.ai  darcydocs.netlify.app;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' docs.darcy.ai  darcydocs.netlify.app asciinema.org www.googletagmanager.com www.google-analytics.com cdn.segment.com netlify-cdp-loader.netlify.app static.ads-twitter.com snap.licdn.com;
      frame-src 'self' 'unsafe-inline' docs.darcy.ai  darcydocs.netlify.app app.netlify.com;
      connect-src 'self' docs.darcy.ai  darcydocs.netlify.app asciinema.org www.google-analytics.com cdn.linkedin.oribi.io  api.segment.io cdn.segment.com;
      img-src 'self' 'unsafe-inline' data: https: docs.darcy.ai  darcydocs.netlify.app www.netlify.com;
      style-src 'self' 'unsafe-inline'  docs.darcy.ai  darcydocs.netlify.app www.netlify.com fonts.googleapis.com;
      font-src 'self' 'unsafe-inline' docs.darcy.ai  darcydocs.netlify.app fonts.googleapis.com cdnjs.cloudflare.com fonts.gstatic.com  fonts.googleapis.com github.com maxcdn.bootstrapcdn.com themes.googleusercontent.com use.fontawesome.com
      '''
