name: Hugo

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Run test script (also runs linter)
      run: npm test


    - name: Build website
      run: npm run build:preview
